### ISSUE TITLE
Remove TrackpadScrollEmulator

### ISSUE THREAD

**Issue by saneyuki** [karen-irc/karen#112]
This project [uses](https://github.com/karen-irc/karen/blob/master/client/js/libs/jquery/tse.js) [jQuery TrackpadScrollEmulator plugin](https://github.com/jnicol/trackpad-scroll-emulator). This plugins gives all platforms a scrollbar which is not displayed like OSX's one if you're not scroll.

These similar plugins are very hacky (= buggy), disables native look & feels of platforms, are not accessible. These satisfies only looks!

Emulating scroll-bar on user-land of browser is very ridiculous. Its emulation makes worst cost-benefit balance.

I'm intent on removing this absolutely.

**Comment by Constellation** [comment]
Strongly agreed. Emulating scrollbar is very problematic.
