### ISSUE TITLE
Send the first time JSON as gzipped content

### ISSUE THREAD

**Issue by Constellation** [karen-irc/karen#143]
Currently, karen start up time is significantly slow with larger data sets.
Seeing the network profiling result, I've found that sending the initial data (including the entire networks, channels, messages) takes a lot of time and it is not gzipped.

**Comment by Constellation** [comment]
possible design is compressing the data sent through WebSocket.

**Comment by Constellation** [comment]
What about using `msgpack`?

**Comment by saneyuki** [comment]
I push protobuf, which must use IDL for messages!

**Comment by saneyuki** [comment]
`Engine.io` (Socket.IO's `Server()` crates it) has [`httpCompression`](https://github.com/Automattic/engine.io#server-2) option.

@Constellation have you seen it?

**Comment by Constellation** [comment]
@saneyuki 

Oops. I just saw the socket.io only. That's really what we want!

**Comment by Constellation** [comment]
If it (httpCompression) solves this problem, I think just using it is better.
After considering msgpack & protobuf, slightly I second msgpack because,

- `protobuf` type is nice. But we already wrote our types in models. I'm worrying about that duplicating it becomes unacceptable burden.
- Maybe we use the protobuf generated object just as serializable representation. Not use it directly as models. So types may be not so beneficial. They should be asserted in the models' side.

**Comment by Constellation** [comment]
Anyway, if `httpCompression` solves the problem, in the meantime, there is not so strong need for introducing `msgpack` or `protobuf`.

**Comment by saneyuki** [comment]
I think your account is reasonable. I agree msgpack is good at now if we cannot use `httpCompression` option.
