### ISSUE TITLE
Adopt external library to convert IRC messages to HTML

### ISSUE THREAD

**Issue by Constellation** [karen-irc/karen#38]
Currently, we are using handmade handlebars' plugin to convert it.

**Comment by Constellation** [comment]
Since triple stash is used for this (handlebars), this function is security critical. So I would like to use well-tested some external libraries.

**Comment by saneyuki** [comment]
I seem it's good that to write codes manipulating a raw DOM APIs :)

Apparently, React will good for this usecase, but I doubt about its performance for this. Message nods will be thousands in the runtime, so I think React's diff computation might be bottle neck. [Immutable.js](http://facebook.github.io/immutable-js/) + [React PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html) may resolve this performance problem, however, at least, it would need to do diff a array which contains messages **for every time when a new message arrived**.

Of course, if we implement a wise cache system for a message view, there might be no problem to use React. But it will not be recently :(

**Comment by Constellation** [comment]
`triple-stash"`

**Comment by Constellation** [comment]
#33, #34

**Comment by saneyuki** [comment]
By #714 and others, we're now using react to construct messages view
